<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Assets\Scripts\Battle\DemoBattleLog.cs" Link="Battle\DemoBattleLog.cs" />
    <Compile Include="..\Assets\Scripts\Battle\DemoBattlePresentationStep.cs" Link="Battle\DemoBattlePresentationStep.cs" />
    <Compile Include="..\Assets\Scripts\Battle\DemoBattleState.cs" Link="Battle\DemoBattleState.cs" />
    <Compile Include="..\Assets\Scripts\Cards\DemoCard.cs" Link="Cards\DemoCard.cs" />
    <Compile Include="..\Assets\Scripts\Cards\DemoCardLibrary.cs" Link="Cards\DemoCardLibrary.cs" />
    <Compile Include="..\Assets\Scripts\Common\SimpleJsonParser.cs" Link="Common\SimpleJsonParser.cs" />
    <Compile Include="..\Assets\Scripts\Combatants\DemoCombatant.cs" Link="Combatants\DemoCombatant.cs" />
    <Compile Include="..\Assets\Scripts\Map\DemoMapRun.cs" Link="Map\DemoMapRun.cs" />
    <Compile Include="..\Assets\Scripts\Rewards\DemoArtifactRewardService.cs" Link="Rewards\DemoArtifactRewardService.cs" />
    <Compile Include="..\Assets\Scripts\Rewards\DemoGongfaRewardService.cs" Link="Rewards\DemoGongfaRewardService.cs" />
    <Compile Include="..\Assets\Scripts\Rewards\DemoReward.cs" Link="Rewards\DemoReward.cs" />
    <Compile Include="..\Assets\Scripts\Rewards\DemoRewardService.cs" Link="Rewards\DemoRewardService.cs" />
    <Compile Include="..\Assets\Scripts\Systems\DemoArtifact.cs" Link="Systems\DemoArtifact.cs" />
    <Compile Include="..\Assets\Scripts\Systems\DemoConfigData.cs" Link="Systems\DemoConfigData.cs" />
    <Compile Include="..\Assets\Scripts\Systems\DemoConfigRepository.cs" Link="Systems\DemoConfigRepository.cs" />
    <Compile Include="..\Assets\Scripts\Systems\DemoGongfa.cs" Link="Systems\DemoGongfa.cs" />
    <Compile Include="..\Assets\Scripts\Systems\DemoQuality.cs" Link="Systems\DemoQuality.cs" />
    <Compile Include="..\Assets\Scripts\Systems\DemoRelic.cs" Link="Systems\DemoRelic.cs" />
    <Compile Include="..\Assets\Scripts\Systems\DemoRunState.cs" Link="Systems\DemoRunState.cs" />
  </ItemGroup>

</Project>
